name: FSL-React-App-Build

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./codebase/rdicidr-0.1.0   

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 15.x
      uses: actions/setup-node@v3
      with:
        node-version: 15.x
  
    - run: npm install
    - run: npm run lint
    - run: |
        npm install prettier
        npm run prettier
    - run: CI=true npm run test
    - run: npm run build